name = "cursorrules"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
pages_build_output_dir = ".next" # 添加这行

[site]
bucket = ".next/static"

[env.production]
vars = { ENVIRONMENT = "production" }