name = "cursorrules"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = ".next"

[env.production]
vars = { ENVIRONMENT = "production" }